// Pre-loaded sample resumes and JD for 1-click interactive testing
export const SAMPLES = {
  strong: {
    title: "Senior Full Stack (High Match)",
    resume: "Aarav Sharma\nSenior Full Stack Engineer\nBengaluru, India | +91 98765 43210 | aarav.sharma.dev@gmail.com\nLinkedIn: linkedin.com/in/aaravsharma-dev | GitHub: github.com/aaravsharma\n\nPROFESSIONAL SUMMARY\nResults-driven Senior Full Stack Engineer with 6+ years of experience designing and scaling high-performance web applications and cloud architectures. Expert in React 18, Node.js, TypeScript, and MongoDB. Proven track record of leading engineering teams, optimizing microservices latency by 45%, and architecting mission-critical platforms handling 12M+ monthly active users on AWS.\n\nTECHNICAL SKILLS\n- Frontend: React.js, Next.js, Redux Toolkit, TypeScript, JavaScript (ES6+), HTML5, CSS3, Tailwind CSS\n- Backend: Node.js, Express.js, REST APIs, GraphQL, Microservices Architecture\n- Databases: MongoDB, PostgreSQL, Redis (Caching), Mongoose\n- Cloud & DevOps: AWS (EC2, S3, ECS, Lambda, CloudFront), Docker, Kubernetes, CI/CD (GitHub Actions)\n- Testing & Tools: Jest, Cypress, Git, Postman, Webpack, esbuild, Agile/Scrum\n\nWORK EXPERIENCE\n\nSenior Full Stack Engineer | Apex Cloud Solutions (2022 - Present)\n- Architected and built 8 core microservices in Node.js and Express deployed on AWS ECS with Docker, cutting API response times from 340ms to 95ms.\n- Spearheaded the redesign of customer dashboard using React 18 and Redux Toolkit, resulting in a 40% reduction in bounce rate and 50% faster page loads.\n- Designed high-throughput MongoDB aggregation pipelines and optimized database indexing, reducing database CPU load by 35%.\n- Implemented robust CI/CD pipelines using GitHub Actions, enabling zero-downtime daily deployments across production environments.\n- Mentored a team of 6 software developers, instituted automated unit testing with Jest achieving 88% test coverage, and led technical design reviews.\n\nFull Stack Software Engineer | Horizon Fintech Labs (2019 - 2022)\n- Engineered scalable payment processing modules in React, Node.js, and TypeScript processing $4M+ in monthly transactions.\n- Integrated Redis distributed caching layer to support high concurrency during peak sale events with 99.99% uptime.\n- Developed role-based authentication and security controls with JWT, OAuth 2.0, and bcrypt encryption.\n- Partnered closely with product managers, UI/UX designers, and DevOps engineers in bi-weekly Agile sprints.\n\nEDUCATION\nBachelor of Technology in Computer Science and Engineering\nNational Institute of Technology (NIT), Surathkal (2015 - 2019) | CGPA: 8.9/10\n\nCERTIFICATIONS\n- AWS Certified Solutions Architect - Associate (2023)\n- MongoDB Certified Developer Associate (2022)\n",
    job: "Senior Full Stack Engineer (React & Node.js)\n\nAbout the Role:\nWe are looking for a Senior Full Stack Engineer to lead architecture and development of our core web platform. You will build high-traffic frontend applications with React and robust backend microservices with Node.js, Express, and MongoDB, deployed on AWS.\n\nKey Responsibilities:\n- Design, develop, and maintain web applications using React 18, TypeScript, and Redux Toolkit.\n- Architect scalable RESTful APIs and microservices using Node.js, Express, and MongoDB.\n- Manage cloud infrastructure on AWS (EC2, S3, ECS, Lambda, CloudFront) with Docker and CI/CD pipelines.\n- Optimize database queries, caching strategies (Redis), and system latency for high-concurrency workloads.\n- Mentor junior software engineers and lead code reviews and automated testing (Jest, Cypress).\n\nRequired Qualifications:\n- 5+ years of full-stack software engineering experience.\n- Deep expertise with JavaScript, TypeScript, React, and Node.js.\n- Strong knowledge of MongoDB, PostgreSQL, and schema design.\n- Hands-on experience with Docker, CI/CD (GitHub Actions), and AWS services.\n- Proven track record of improving system performance and delivery velocity.\n- Bachelor's degree in Computer Science or equivalent practical experience.\n"
  },
  weak: {
    title: "Entry-Level Office (Low Match)",
    resume: "Rahul\nemail: rahul123@yahoo.com\n\nABOUT ME\ni am a hardworking person looking for a good computer job in IT company. I want to learn new things and work hard for company growth.\n\nWORK EXPERIANCE\nhelper / assistant (2022 - 2023)\n- helped in office work and data entry in excel\n- attended phone calls from customers\n- fixed printer issues and restarted computers\n\nShop helper (2021 - 2022)\n- billing and counting items\n- talking with customers\n\nSKILLS\n- MS Office, MS Excel, Word\n- Typing fast\n- Internet browsing\n- hard working\n- team player\n\nEDUCATION\n12th pass from State Board (2020)\n10th pass (2018)\n\nHOBBIES\nPlaying cricket, watching movies, listening to songs.\n",
    job: "Senior Full Stack Engineer (React & Node.js)\n\nAbout the Role:\nWe are looking for a Senior Full Stack Engineer to lead architecture and development of our core web platform. You will build high-traffic frontend applications with React and robust backend microservices with Node.js, Express, and MongoDB, deployed on AWS.\n\nKey Responsibilities:\n- Design, develop, and maintain web applications using React 18, TypeScript, and Redux Toolkit.\n- Architect scalable RESTful APIs and microservices using Node.js, Express, and MongoDB.\n- Manage cloud infrastructure on AWS (EC2, S3, ECS, Lambda, CloudFront) with Docker and CI/CD pipelines.\n- Optimize database queries, caching strategies (Redis), and system latency for high-concurrency workloads.\n- Mentor junior software engineers and lead code reviews and automated testing (Jest, Cypress).\n\nRequired Qualifications:\n- 5+ years of full-stack software engineering experience.\n- Deep expertise with JavaScript, TypeScript, React, and Node.js.\n- Strong knowledge of MongoDB, PostgreSQL, and schema design.\n- Hands-on experience with Docker, CI/CD (GitHub Actions), and AWS services.\n- Proven track record of improving system performance and delivery velocity.\n- Bachelor's degree in Computer Science or equivalent practical experience.\n"
  }
};
